language: node_js

node_js:
  - 'lts/*'

cache:
  directories:
    - "node_modules"

after_success:
  - npm run generate:docs

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master
